global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']
  - job_name: account-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3002']
  - job_name: ledger-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3003']
  - job_name: transaction-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3004']
  - job_name: fraud-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3005']
  - job_name: notification-service
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3006']
